# Generated by Django 4.0.1 on 2023-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallerymodel_options'),
        ('Order', '0004_alter_order_product_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.VariationModel'),
        ),
    ]
